import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Autogenerated until all docs are migrated; will be replaced with explicit sidebar
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

export default sidebars;
